server:
  port: 8087

spring:
  application:
    name: system-monitor
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

knife4j:
  enable: true
  setting:
    language: zh-CN

logging:
  level:
    com.zhuji.monitor: DEBUG
    org.springframework.boot.actuate: DEBUG