server:
  port: 8085

spring:
  application:
    name: third-party-service

feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 30000
        loggerLevel: basic

knife4j:
  enable: true
  setting:
    language: zh-CN

logging:
  level:
    com.zhuji: DEBUG
    feign: DEBUG